# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-06 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.TextField(max_length=5000, verbose_name='\u7559\u8a00\u4fe1\u606f'),
        ),
    ]
